import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.css";
import NavBar from "@/components/navbar/NavBar";
import SocialNav from "@/components/navbar/SocialNav";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SocialNav />
        <NavBar />
        <main className="container">{children}</main>
      </body>
    </html>
  );
}
